---
title: "Mathur_Johri_Jakobs_Pourhamidi_Final_Project"
author: "Abeer Mathur, Marvin Jakobs, Divyesh Johri, Cinah Pourhamidi"
date: "2022-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(readr)
```
### TASK 1

#### Load in datasets
```{r message=FALSE, warning=FALSE}
CODGameModes <- read.csv("https://raw.githubusercontent.com/Abeermathur7/STAT380Final/main/CODGameModes.csv")
CODGames_p1_380 <- read.csv("https://raw.githubusercontent.com/Abeermathur7/STAT380Final/main/CODGames_p1_380.csv")
CODGames_p2_380 <- read.csv("https://raw.githubusercontent.com/Abeermathur7/STAT380Final/main/CODGames_p2_380.csv")
```

#### Research Question: Which game mode is most likely to reach the score limit? 
```{r message=FALSE, warning=FALSE}
CODGames<- rbind(CODGames_p1_380,CODGames_p2_380) #combine raw data

dupModes <- CODGameModes
dupModes$Mode <- paste("HC -", dupModes$Mode) #adding HC mode limits
allModes <- rbind(dupModes,CODGameModes)

scoreLimit <- left_join(CODGames,allModes, by = c("GameType"="Mode")) #add score limit column

scoreLimit <- tidyr::separate(data = scoreLimit, col = Result, sep = "-", into = c("score1","score2")) #put each team score into individual columns

scoreLimit <- mutate(scoreLimit, limitReached = ifelse(score1 == ScoreLimit | score2 == ScoreLimit,1,0)) #note if either team reached the limit
         
limitList <- scoreLimit %>% group_by(GameType) %>% tally(limitReached) #group by and count games that reached score limit for each mode
totalCount <- scoreLimit %>% group_by(GameType) %>% summarise(count = n()) #total games of each mode played
limitList$total <- totalCount$count 
limitList <- mutate(limitList, limitProb = n/total) #find ratio of score limit reached to games played
limitList %>% arrange(desc(limitProb)) #print descending
```
```{r}
ggplot(limitList, aes(x=GameType,y=limitProb)) + 
  geom_bar(stat = "identity", fill = "#301934") + 
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  ylab("Prob of Score Limit Reached")
```
